### ISSUE TITLE
Traceback with Blender 2.78b

### ISSUE THREAD

**Issue by Spirou4D** [ucupumar/hdr-2-rgbm#1]
Hi Ucupumar,

Here is my last traceback this morning with the new release of Blender 2.78b:
`Traceback (most recent call last):
  File "/home/patrinux/.config/blender/2.78/scripts/addons/hdr_2_rgbm/__init__.py", line 101, in load_node_groups
    folder = [x for x in dirs if x == 'hdr-2-rgbm' or x == 'hdr-2-rgbm-master'][0]
IndexError: list index out of range

At soon...
Spirou4D
`

**Comment by ucupumar** [comment]
I think you changed your addon folder name, it should be 'hdr-2-rgbm' or 'hdr-2-rgbm-master'.

**Comment by Spirou4D** [comment]
Ho yes absolutely and now no problem!
Thanks a lot for your remark!
I havn't not read the traceback....
Good Luck.
Spirou4D

**Comment by ucupumar** [comment]
Ok, I'm closing this issue.
